/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Animal, GeneticParameters, SelectionIndexConfig } from '../types';

export const initialAnimals: Animal[] = [
  // ==========================================
  // BOVINOS DE CORTE (Nelore, Angus, Cruzados, Braford, Senepol)
  // ==========================================
  // --- FOUNDERS / FUNDADORES (Sem Pais Registrados) ---
  {
    id: "BOV-F01",
    name: "Nelore Provado - Cabanha Alvorada",
    species: "bovino",
    sex: "M",
    birthDate: "2017-09-12",
    birthYear: 2017,
    sireId: null,
    damId: null,
    breedComp: { "Nelore": 1.0 },
    rebanho: "Fazenda_Pampa",
    manejo: "Pasto",
    phenotypes: {}, // Parent founder sem fenótipo próprio (alta acurácia por teste de progênie)
    rfid: "982 123000004512",
    genomicTested: true,
    gepds: {
      pesoDesmame: 12.8,
      pesoSobreano: 22.4,
      pe: 1.45,
      aol: 4.2,
      egs: 0.85
    },
    genomicAccuracies: {
      pesoDesmame: 0.82,
      pesoSobreano: 0.85,
      pe: 0.79,
      aol: 0.81,
      egs: 0.75
    }
  },
  {
    id: "BOV-F02",
    name: "Angus Black - Red Vigor Legend",
    species: "bovino",
    sex: "M",
    birthDate: "2017-10-05",
    birthYear: 2017,
    sireId: null,
    damId: null,
    breedComp: { "Angus": 1.0 },
    rebanho: "Fazenda_Pampa",
    manejo: "Pasto",
    phenotypes: {}, // Parent founder
    rfid: "982 123000004515",
    genomicTested: true,
    gepds: {
      pesoDesmame: 8.5,
      pesoSobreano: 18.9,
      pe: 0.95,
      aol: 3.8,
      egs: 1.45
    },
    genomicAccuracies: {
      pesoDesmame: 0.79,
      pesoSobreano: 0.83,
      pe: 0.74,
      aol: 0.78,
      egs: 0.72
    }
  },
  {
    id: "BOV-F03",
    name: "Senepol Puro - Red Bull Campeão",
    species: "bovino",
    sex: "M",
    birthDate: "2018-05-15",
    birthYear: 2018,
    sireId: null,
    damId: null,
    breedComp: { "Senepol": 1.0 },
    rebanho: "Fazenda_Planalto",
    manejo: "Suplementado",
    phenotypes: {} // Parent founder
  },
  {
    id: "BOV-F04",
    name: "Doadora Nelore Elite S04",
    species: "bovino",
    sex: "F",
    birthDate: "2018-08-20",
    birthYear: 2018,
    sireId: null,
    damId: null,
    breedComp: { "Nelore": 1.0 },
    rebanho: "Fazenda_Pampa",
    manejo: "Pasto",
    phenotypes: {
      pesoNascimento: 29.5,
      pesoDesmame: 210,
      pesoSobreano: 380,
      gmd: 720,
      ipp: 710,
      iep: 405,
      aol: 61.2,
      egs: 3.0,
      marmoreio: 1.2,
      car: -0.15,
      temperamento: 2,
      resistenciaCarrapato: 4,
      stayability: 82,
      epmur_E: 4,
      epmur_P: 4,
      epmur_M: 4,
      epmur_U: 3,
      epmur_R: 4
    }
  },
  {
    id: "BOV-F05",
    name: "Matriz Angus Red 15 - Sul",
    species: "bovino",
    sex: "F",
    birthDate: "2018-06-18",
    birthYear: 2018,
    sireId: null,
    damId: null,
    breedComp: { "Angus": 1.0 },
    rebanho: "Fazenda_Pampa",
    manejo: "Pasto",
    phenotypes: {
      pesoNascimento: 32.0,
      pesoDesmame: 228,
      pesoSobreano: 410,
      gmd: 810,
      ipp: 690,
      iep: 385,
      aol: 68.5,
      egs: 4.8,
      marmoreio: 3.8,
      car: -0.32,
      temperamento: 1,
      resistenciaCarrapato: 2,
      stayability: 75,
      epmur_E: 4,
      epmur_P: 4,
      epmur_M: 4,
      epmur_U: 4,
      epmur_R: 4
    }
  },
  {
    id: "BOV-F06",
    name: "Matriz Hereford Pura - Fronteira",
    species: "bovino",
    sex: "F",
    birthDate: "2018-11-03",
    birthYear: 2018,
    sireId: null,
    damId: null,
    breedComp: { "Hereford": 1.0 },
    rebanho: "Fazenda_Pampa",
    manejo: "Pasto",
    phenotypes: {
      pesoNascimento: 31.0,
      pesoDesmame: 215,
      pesoSobreano: 395,
      gmd: 750,
      ipp: 730,
      iep: 395,
      aol: 64.0,
      egs: 4.2,
      marmoreio: 2.5,
      car: 0.05,
      temperamento: 1,
      resistenciaCarrapato: 2,
      stayability: 78,
      epmur_E: 4,
      epmur_P: 3,
      epmur_M: 4,
      epmur_U: 4,
      epmur_R: 4
    }
  },

  // --- GENERATION 1 / MATRIZES EM PRODUÇÃO (Filhas dos Fundadores) ---
  {
    id: "BOV-M01",
    name: "Doadora Nelore Elite 502",
    species: "bovino",
    sex: "F",
    birthDate: "2020-08-20",
    birthYear: 2020,
    sireId: "BOV-F01",
    damId: "BOV-F04",
    breedComp: { "Nelore": 1.0 },
    rebanho: "Fazenda_Pampa",
    manejo: "Pasto",
    phenotypes: {
      pesoNascimento: 31.0,
      pesoDesmame: 222,
      pesoSobreano: 405,
      gmd: 800,
      ipp: 720,
      iep: 412,
      aol: 63.8,
      egs: 3.4,
      marmoreio: 1.7,
      car: -0.22,
      temperamento: 2,
      resistenciaCarrapato: 4,
      stayability: 89,
      epmur_E: 4,
      epmur_P: 5,
      epmur_M: 5,
      epmur_U: 3,
      epmur_R: 5
    }
  },
  {
    id: "BOV-M02",
    name: "Matriz F1 Angus-Nelore G1",
    species: "bovino",
    sex: "F",
    birthDate: "2020-11-15",
    birthYear: 2020,
    sireId: "BOV-F02",
    damId: "BOV-F04",
    breedComp: { "Angus": 0.5, "Nelore": 0.5 },
    rebanho: "Fazenda_Pampa",
    manejo: "Pasto",
    phenotypes: {
      pesoNascimento: 33.5,
      pesoDesmame: 242,
      pesoSobreano: 458,
      gmd: 940,
      ipp: 660,
      iep: 380,
      aol: 73.2,
      egs: 5.6,
      marmoreio: 3.4,
      car: -0.41,
      temperamento: 1,
      resistenciaCarrapato: 3,
      stayability: 85,
      epmur_E: 5,
      epmur_P: 5,
      epmur_M: 5,
      epmur_U: 4,
      epmur_R: 4
    }
  },
  {
    id: "BOV-M03",
    name: "Matriz Braford Seleção 27",
    species: "bovino",
    sex: "F",
    birthDate: "2021-02-10",
    birthYear: 2021,
    sireId: "BOV-F01",
    damId: "BOV-F06",
    breedComp: { "Hereford": 0.5, "Nelore": 0.5 },
    rebanho: "Fazenda_Pampa",
    manejo: "Pasto",
    phenotypes: {
      pesoNascimento: 32.5,
      pesoDesmame: 220,
      pesoSobreano: 408,
      gmd: 780,
      ipp: 705,
      iep: 390,
      aol: 66.4,
      egs: 4.5,
      marmoreio: 2.1,
      epmur_E: 4,
      epmur_P: 4,
      epmur_M: 4,
      epmur_U: 4,
      epmur_R: 4
    }
  },
  {
    id: "BOV-M04",
    name: "Matriz Brangus Real M04",
    species: "bovino",
    sex: "F",
    birthDate: "2021-04-22",
    birthYear: 2021,
    sireId: "BOV-F02",
    damId: "BOV-M01",
    breedComp: { "Angus": 0.5, "Nelore": 0.5 },
    rebanho: "Fazenda_Pampa",
    manejo: "Pasto",
    phenotypes: {
      pesoNascimento: 32.8,
      pesoDesmame: 235,
      pesoSobreano: 435,
      gmd: 885,
      ipp: 685,
      iep: 375,
      aol: 71.0,
      egs: 5.1,
      marmoreio: 3.0,
      epmur_E: 4,
      epmur_P: 5,
      epmur_M: 5,
      epmur_U: 4,
      epmur_R: 4
    }
  },
  {
    id: "BOV-M05",
    name: "Novilha Nelore Precoce M05",
    species: "bovino",
    sex: "F",
    birthDate: "2021-08-30",
    birthYear: 2021,
    sireId: "BOV-F01",
    damId: "BOV-F04",
    breedComp: { "Nelore": 1.0 },
    rebanho: "Fazenda_Pampa",
    manejo: "Pasto",
    phenotypes: {
      pesoNascimento: 30.0,
      pesoDesmame: 218,
      pesoSobreano: 395,
      gmd: 760,
      ipp: 698,
      iep: 388,
      aol: 62.1,
      egs: 3.1,
      marmoreio: 1.5,
      epmur_E: 4,
      epmur_P: 4,
      epmur_M: 4,
      epmur_U: 3,
      epmur_R: 4
    }
  },
  {
    id: "BOV-M06",
    name: "Matriz Senepol Cruzada F1",
    species: "bovino",
    sex: "F",
    birthDate: "2021-09-02",
    birthYear: 2021,
    sireId: "BOV-F03",
    damId: "BOV-F04",
    breedComp: { "Senepol": 0.5, "Nelore": 0.5 },
    rebanho: "Fazenda_Planalto",
    manejo: "Suplementado",
    phenotypes: {
      pesoNascimento: 31.8,
      pesoDesmame: 226,
      pesoSobreano: 425,
      gmd: 840,
      ipp: 715,
      iep: 395,
      aol: 67.8,
      egs: 4.0,
      marmoreio: 2.2,
      epmur_E: 4,
      epmur_P: 4,
      epmur_M: 4,
      epmur_U: 3,
      epmur_R: 4
    }
  },

  // --- GENERATION 2 / JOVENS PROMISSAS E REPRODUTORES ATIVOS (Onde a mágica do melhoramento acontece) ---
  {
    id: "BOV-A01",
    name: "Tourinho Nelore Pampa",
    species: "bovino",
    sex: "M",
    birthDate: "2023-08-25",
    birthYear: 2023,
    sireId: "BOV-F01",
    damId: "BOV-M01", // Mating Sire Bov-F01 with daughters Bov-M01. Demonstrates 25% inbreeding coefficient F!
    breedComp: { "Nelore": 1.0 },
    rebanho: "Fazenda_Pampa",
    manejo: "Semiextensivo",
    phenotypes: {
      pesoNascimento: 34.2,
      pesoDesmame: 251,
      pesoSobreano: 495,
      gmd: 980,
      pe: 37.5,
      aol: 80.5,
      egs: 5.1,
      marmoreio: 2.0,
      epmur_E: 4,
      epmur_P: 5,
      epmur_M: 5,
      epmur_U: 3,
      epmur_R: 4
    }
  },
  {
    id: "BOV-A02",
    name: "Novilha Brangus Pampa 1",
    species: "bovino",
    sex: "F",
    birthDate: "2024-03-02",
    birthYear: 2024,
    sireId: "BOV-F02",
    damId: "BOV-M02", // Backcross to Angus
    breedComp: { "Angus": 0.75, "Nelore": 0.25 },
    rebanho: "Fazenda_Pampa",
    manejo: "Semiextensivo",
    phenotypes: {
      pesoNascimento: 33.0,
      pesoDesmame: 226,
      pesoSobreano: 432,
      gmd: 845,
      ipp: null, // Ainda jovem
      iep: null,
      aol: 70.8,
      egs: 6.4,
      marmoreio: 4.4,
      epmur_E: 4,
      epmur_P: 4,
      epmur_M: 4,
      epmur_U: 5,
      epmur_R: 4
    }
  },
  {
    id: "BOV-A03",
    name: "Bezerro Nelore Novidade",
    species: "bovino",
    sex: "M",
    birthDate: "2024-09-10",
    birthYear: 2024,
    sireId: "BOV-A01", // Inbred sire
    damId: "BOV-M01",
    breedComp: { "Nelore": 1.0 },
    rebanho: "Fazenda_Pampa",
    manejo: "Semiextensivo",
    phenotypes: {
      pesoNascimento: 35.8,
      pesoDesmame: 268,
      pesoSobreano: 524,
      gmd: 1060,
      pe: 39.2,
      aol: 84.6,
      egs: 4.2,
      marmoreio: 2.4,
      epmur_E: 5,
      epmur_P: 5,
      epmur_M: 5,
      epmur_U: 3,
      epmur_R: 5
    }
  },
  {
    id: "BOV-A04",
    name: "Bezerra F2 Pampa",
    species: "bovino",
    sex: "F",
    birthDate: "2024-11-20",
    birthYear: 2024,
    sireId: "BOV-A01",
    damId: "BOV-M02",
    breedComp: { "Nelore": 0.75, "Angus": 0.25 },
    rebanho: "Fazenda_Pampa",
    manejo: "Semiextensivo",
    phenotypes: {
      pesoNascimento: 31.5,
      pesoDesmame: 224,
      pesoSobreano: 418,
      gmd: 855,
      aol: 75.8,
      egs: 4.9,
      marmoreio: 3.0,
      epmur_E: 4,
      epmur_P: 4,
      epmur_M: 5,
      epmur_U: 4,
      epmur_R: 4
    }
  },
  {
    id: "BOV-A05",
    name: "Tourinho Braford Provador",
    species: "bovino",
    sex: "M",
    birthDate: "2023-09-15",
    birthYear: 2023,
    sireId: "BOV-F01",
    damId: "BOV-M03",
    breedComp: { "Hereford": 0.25, "Nelore": 0.75 },
    rebanho: "Fazenda_Pampa",
    manejo: "Semiextensivo",
    phenotypes: {
      pesoNascimento: 33.0,
      pesoDesmame: 240,
      pesoSobreano: 465,
      gmd: 910,
      pe: 38.0,
      aol: 76.5,
      egs: 4.6,
      marmoreio: 2.8,
      epmur_E: 4,
      epmur_P: 4,
      epmur_M: 5,
      epmur_U: 4,
      epmur_R: 4
    }
  },
  {
    id: "BOV-A06",
    name: "Doadora Brangus Prime G2",
    species: "bovino",
    sex: "F",
    birthDate: "2023-09-02",
    birthYear: 2023,
    sireId: "BOV-F02",
    damId: "BOV-M01",
    breedComp: { "Angus": 0.5, "Nelore": 0.5 },
    rebanho: "Fazenda_Planalto",
    manejo: "Suplementado",
    phenotypes: {
      pesoNascimento: 32.2,
      pesoDesmame: 238,
      pesoSobreano: 450,
      gmd: 905,
      ipp: null,
      iep: null,
      aol: 72.4,
      egs: 5.8,
      marmoreio: 3.8,
      epmur_E: 4,
      epmur_P: 5,
      epmur_M: 5,
      epmur_U: 4,
      epmur_R: 4
    }
  },
  {
    id: "BOV-A07",
    name: "Novilha Cruzada Senepol G2",
    species: "bovino",
    sex: "F",
    birthDate: "2023-11-05",
    birthYear: 2023,
    sireId: "BOV-F03",
    damId: "BOV-M01",
    breedComp: { "Senepol": 0.5, "Nelore": 0.5 },
    rebanho: "Fazenda_Planalto",
    manejo: "Suplementado",
    phenotypes: {
      pesoNascimento: 32.0,
      pesoDesmame: 230,
      pesoSobreano: 438,
      gmd: 870,
      ipp: null,
      iep: null,
      aol: 70.2,
      egs: 4.6,
      marmoreio: 2.5,
      epmur_E: 4,
      epmur_P: 4,
      epmur_M: 4,
      epmur_U: 3,
      epmur_R: 4
    }
  },
  {
    id: "BOV-A08",
    name: "Novilha Nelore Reposição Progeny",
    species: "bovino",
    sex: "F",
    birthDate: "2023-12-01",
    birthYear: 2023,
    sireId: "BOV-F01",
    damId: "BOV-M05",
    breedComp: { "Nelore": 1.0 },
    rebanho: "Fazenda_Planalto",
    manejo: "Suplementado",
    phenotypes: {
      pesoNascimento: 28.5,
      pesoDesmame: 202,
      pesoSobreano: 372,
      gmd: 700,
      ipp: null,
      iep: null,
      aol: 59.8,
      egs: 3.2,
      marmoreio: 1.4,
      epmur_E: 4,
      epmur_P: 3,
      epmur_M: 4,
      epmur_U: 3,
      epmur_R: 4
    }
  },

];

export const defaultGeneticParameters: GeneticParameters = {
  h2_pesoDesmame: 0.24,
  h2_pesoSobreano: 0.32,
  h2_pe: 0.41,
  h2_aol: 0.35,
  h2_egs: 0.28,

  var_g_pesoDesmame: 42.0,
  var_g_pesoSobreano: 110.0,
  var_g_pe: 2.50,
  var_g_aol: 12.0,
  var_g_egs: 0.45,

  var_e_pesoDesmame: 133.0,
  var_e_pesoSobreano: 233.75,
  var_e_pe: 3.59,
  var_e_aol: 22.28,
  var_e_egs: 1.15
};

export const defaultSelectionIndexConfig: SelectionIndexConfig = {
  name: "Índice de Produtividade em Carne Pampa",
  weight_pesoDesmame: 1.2,  // Emphasis on maternal growth
  weight_pesoSobreano: 1.8, // Heavy influence on visual slaughter weight
  weight_pe: 1.5,           // Reproductive indicator
  weight_aol: 2.5,          // Carcass ribeye area muscularity
  weight_egs: 0.8           // Backfat buffer
};
